In [44]:
import re
import random
import warnings
from pathlib import Path
from collections import Counter

import numpy as np
import pandas as pd

from tqdm.auto import tqdm
from tqdm.auto import trange
import time

from corus import load_lenta

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report
from sklearn.feature_extraction.text import TfidfVectorizer

from gensim.models import Word2Vec, KeyedVectors
import gensim.downloader as api

import matplotlib.pyplot as plt
import seaborn as sns

from navec import Navec

In [4]:
warnings.filterwarnings("ignore")

RANDOM_STATE = 42
random.seed(RANDOM_STATE)
np.random.seed(RANDOM_STATE)

In [5]:
DATA_PATH = Path("lenta-ru-news.csv.gz")
print(DATA_PATH)

if not DATA_PATH.exists():
    !wget -O lenta-ru-news.csv.gz https://github.com/yutkin/Lenta.Ru-News-Dataset/releases/download/v1.0/lenta-ru-news.csv.gz

assert DATA_PATH.exists(), "Не удалось скачать lenta-ru-news.csv.gz"
DATA_PATH

lenta-ru-news.csv.gz

PosixPath('lenta-ru-news.csv.gz')

In [6]:
rows = []

for rec in tqdm(load_lenta(str(DATA_PATH)), desc="Loading lenta"):
    rows.append({
        "title": rec.title,
        "text": rec.text,
        "topic": rec.topic
    })

df = pd.DataFrame(rows)
df.head()

Loading lenta: 0it [00:00, ?it/s]

,title,text,topic
0,Названы регионы России с самой высокой смертно...,Вице-премьер по социальным вопросам Татьяна Го...,Россия
1,Австрия не представила доказательств вины росс...,Австрийские правоохранительные органы не предс...,Спорт
2,Обнаружено самое счастливое место на планете,Сотрудники социальной сети Instagram проанализ...,Путешествия
3,В США раскрыли сумму расходов на расследование...,С начала расследования российского вмешательст...,Мир
4,Хакеры рассказали о планах Великобритании зами...,Хакерская группировка Anonymous опубликовала н...,Мир

In [7]:
print(df.shape)
df.info()

(739351, 3)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 739351 entries, 0 to 739350
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   title   739351 non-null  object
 1   text    739351 non-null  object
 2   topic   739351 non-null  object
dtypes: object(3)
memory usage: 16.9+ MB

In [8]:
# Убираем пустые и пробельные темы
df["topic"] = df["topic"].astype(str).str.strip()
df = df[df["topic"] != ""].copy()

print(df.shape)
print(df["topic"].nunique())

(739148, 3)
23

In [9]:
MIN_CLASS_SIZE = 100
# убираю слишком редкие классы, чтобы стратификация и оценка были стабильнее

topic_counts = df["topic"].value_counts()
valid_topics = topic_counts[topic_counts >= MIN_CLASS_SIZE].index
df = df[df["topic"].isin(valid_topics)].copy()

print(df.shape)
print(df["topic"].nunique())

(739076, 3)
18

In [58]:
N_SAMPLES = 100_000

if len(df) > N_SAMPLES:
    df_sample, _ = train_test_split(
        df,
        train_size=N_SAMPLES,
        stratify=df["topic"],
        random_state=RANDOM_STATE
    )
else:
    df_sample = df.copy()

df_sample = df_sample.reset_index(drop=True)

print(df_sample.shape)
print((df_sample["topic"].value_counts(normalize=True) * 100).round(2).head(10))

(100000, 3)
topic
Россия             21.72
Мир                18.49
Экономика          10.76
Спорт               8.72
Культура            7.28
Бывший СССР         7.22
Наука и техника     7.19
Интернет и СМИ      6.04
Из жизни            3.74
Дом                 2.94
Name: proportion, dtype: float64

In [59]:
URL_RE = re.compile(r"https?://\S+|www\.\S+")
NON_WORD_RE = re.compile(r"[^0-9a-zа-яё\- ]+", flags=re.IGNORECASE)
MULTISPACE_RE = re.compile(r"\s+")

# не делаю стемминг/лемматизацию для word2vec, чтобы не терять различия словоформ и не усложнять пайплайн

def normalize_text(title: str, text: str) -> str:
    s = f"{title} {text}".lower()
    s = s.replace("\xa0", " ")
    s = URL_RE.sub(" ", s)
    s = NON_WORD_RE.sub(" ", s)
    s = MULTISPACE_RE.sub(" ", s).strip()
    return s

tqdm.pandas()

df_sample["clean_text"] = df_sample.progress_apply(
    lambda row: normalize_text(row["title"], row["text"]),
    axis=1
)

df_sample = df_sample[df_sample["clean_text"] != ""].reset_index(drop=True)
df_sample[["title", "topic", "clean_text"]].head()

  0%|          | 0/100000 [00:00<?, ?it/s]

,title,topic,clean_text
0,Подросток стрелял по людям из пневматического ...,Россия,подросток стрелял по людям из пневматического ...
1,Япония запустила самую маленькую ракету-носитель,Наука и техника,япония запустила самую маленькую ракету-носите...
2,Основатель «Пятерочки» продаст отель-усадьбу в...,Дом,основатель пятерочки продаст отель-усадьбу в к...
3,"На Украине опубликуют ""черный список антисемитов""",Бывший СССР,на украине опубликуют черный список антисемито...
4,Россия приступила к разработке аппарата для ис...,Наука и техника,россия приступила к разработке аппарата для ис...

In [60]:
def tokenize(text: str):
    return text.split()

df_sample["tokens"] = df_sample["clean_text"].progress_apply(tokenize)
df_sample = df_sample[df_sample["tokens"].map(len) > 0].reset_index(drop=True)

df_sample[["clean_text", "tokens"]].head()

  0%|          | 0/100000 [00:00<?, ?it/s]

,clean_text,tokens
0,подросток стрелял по людям из пневматического ...,"[подросток, стрелял, по, людям, из, пневматиче..."
1,япония запустила самую маленькую ракету-носите...,"[япония, запустила, самую, маленькую, ракету-н..."
2,основатель пятерочки продаст отель-усадьбу в к...,"[основатель, пятерочки, продаст, отель-усадьбу..."
3,на украине опубликуют черный список антисемито...,"[на, украине, опубликуют, черный, список, анти..."
4,россия приступила к разработке аппарата для ис...,"[россия, приступила, к, разработке, аппарата, ..."

In [61]:
# df_sample = df_sample[:1000]

In [62]:
train_df, temp_df = train_test_split(
    df_sample,
    test_size=0.4,
    stratify=df_sample["topic"],
    random_state=RANDOM_STATE
)

valid_df, test_df = train_test_split(
    temp_df,
    test_size=0.5,
    stratify=temp_df["topic"],
    random_state=RANDOM_STATE
)

train_df = train_df.reset_index(drop=True)
valid_df = valid_df.reset_index(drop=True)
test_df = test_df.reset_index(drop=True)

print(train_df.shape, valid_df.shape, test_df.shape)

(60000, 5) (20000, 5) (20000, 5)

In [63]:
X_train_text = train_df["clean_text"].tolist()
X_valid_text = valid_df["clean_text"].tolist()
X_test_text  = test_df["clean_text"].tolist()

X_train_tokens = train_df["tokens"].tolist()
X_valid_tokens = valid_df["tokens"].tolist()
X_test_tokens  = test_df["tokens"].tolist()

y_train = train_df["topic"].values
y_valid = valid_df["topic"].values
y_test  = test_df["topic"].values

## Word2Vec

In [64]:
w2v_model = Word2Vec(
    vector_size=200,
    window=5, # компромисс между локальным и более широким контекстом
    min_count=5, # отсекаем шумные токены
    workers=4,
    sg=1, # skip-gram лучше работает с редкими словами
    negative=10,
    seed=RANDOM_STATE
)

print("словарь...")
t0 = time.time()
w2v_model.build_vocab(X_train_tokens)
print(f"словарь построен за {time.time() - t0} сек")
print(f"Размер словаря: {w2v_model.corpus_total_words:,} токенов, {len(w2v_model.wv):,} уникальных слов")

print("обучение...")
for epoch in trange(10, desc="Training w2v"):
    t0 = time.time()
    w2v_model.train(
        X_train_tokens,
        total_examples=w2v_model.corpus_count,
        epochs=1
    )
    print(f"Эпоха {epoch + 1} завершена за {time.time() - t0} сек")

w2v_kv = w2v_model.wv
print(f"Размерность эмбеддингов: {w2v_kv.vector_size}")

словарь...
словарь построен за 4.101820707321167 сек
Размер словаря: 11,275,994 токенов, 108,227 уникальных слов
обучение...

Training w2v:   0%|          | 0/10 [00:00<?, ?it/s]

Эпоха 1 завершена за 47.045875787734985 сек
Эпоха 2 завершена за 46.24284100532532 сек
Эпоха 3 завершена за 46.56093788146973 сек
Эпоха 4 завершена за 46.744221210479736 сек
Эпоха 5 завершена за 46.28986692428589 сек
Эпоха 6 завершена за 46.34423756599426 сек
Эпоха 7 завершена за 47.247162103652954 сек
Эпоха 8 завершена за 45.938313245773315 сек
Эпоха 9 завершена за 47.612446308135986 сек
Эпоха 10 завершена за 46.00763130187988 сек
Размерность эмбеддингов: 200

In [65]:
print(w2v_kv.index_to_key[:500])

['в', 'на', 'и', 'по', 'что', 'с', 'не', 'из', 'о', 'года', 'за', 'как', 'к', '-', 'для', 'его', 'а', 'этом', 'он', 'от', 'об', 'также', 'сообщает', 'россии', 'до', 'году', 'был', 'после', 'будет', 'время', 'это', 'при', 'у', 'сша', 'со', 'были', 'во', 'того', 'заявил', 'словам', 'долларов', 'было', 'однако', '1', 'ранее', 'их', 'том', 'который', 'тысяч', 'человек', 'уже', 'которые', 'но', 'более', 'они', 'ее', 'еще', 'рублей', 'около', 'все', 'данным', 'компании', 'процентов', 'под', 'так', 'была', '2', 'лет', '5', 'этого', 'то', 'будут', 'процента', 'же', 'может', 'миллионов', 'она', 'только', 'кроме', 'чтобы', 'страны', '3', 'новости', 'или', 'является', 'из-за', 'несколько', 'риа', 'один', 'тем', 'суд', 'рф', 'президента', 'пока', '4', 'власти', 'the', 'результате', 'между', 'президент', 'украины', 'два', '10', '6', 'против', 'мы', 'сообщил', 'когда', 'если', 'решение', 'области', 'ссылкой', 'глава', 'которая', 'всего', 'компания', 'где', 'я', '20', 'которых', 'них', '7', 'отметил', 'миллиона', 'передает', 'агентство', 'москвы', 'частности', 'сайте', 'сообщается', 'москве', 'сентября', 'связи', 'свою', '8', 'три', '15', 'быть', 'двух', 'марта', '30', 'миллиарда', 'через', 'год', 'декабря', 'ходе', 'которого', 'информации', 'которой', 'июля', 'января', 'ноября', 'октября', 'июня', 'пишет', 'чем', 'мая', 'место', 'этот', '12', 'дело', 'числе', 'сказал', 'территории', 'стал', 'города', 'апреля', 'этой', 'россия', 'ему', 'раз', 'мира', 'августа', 'согласно', 'мнению', 'стало', 'могут', 'интерфакс', 'своей', '9', '11', 'сейчас', 'безопасности', 'без', 'февраля', 'газета', '2009', 'организации', 'день', 'миллиардов', 'настоящее', 'других', 'известно', 'представители', 'всех', '2008', 'говорится', 'среди', 'российских', 'партии', 'рассказал', 'бы', '25', 'человека', 'над', 'стороны', '14', '2010', 'тысячи', 'участие', 'сообщалось', 'времени', 'владимир', 'удалось', 'работы', '16', 'часть', 'можно', 'есть', 'себя', 'правительства', 'первый', 'одного', '2012', 'им', 'эти', '2011', 'тогда', 'должны', 'начале', 'сми', 'перед', 'конце', 'него', 'котором', 'напомним', 'представитель', 'получил', 'министр', 'погибли', 'случае', 'дома', 'нет', '18', 'мвд', '13', 'своих', 'момент', 'отмечает', 'евро', '17', 'образом', 'больше', 'российской', 'вместе', 'главы', 'должен', 'республики', 'сообщили', '2014', 'рамках', 'течение', 'ни', 'правительство', 'ру', 'полиции', 'людей', 'находится', 'бывший', 'российского', 'таким', 'составляет', 'одной', '0', 'именно', 'отношении', 'александр', 'второй', 'путин', '24', 'стран', '19', 'среду', 'метров', 'понедельник', 'стали', 'дела', 'лишь', 'ли', '2007', '50', 'городе', 'вторник', 'заявили', 'части', 'получили', 'свои', 'пять', 'издание', 'сергей', 'государства', '22', 'новый', '2015', 'суда', 'управления', 'четыре', 'reuters', 'стране', 'четверг', 'качестве', 'своего', 'районе', 'сборной', 'акции', 'месте', 'менее', 'акций', 'группы', 'начала', 'сам', 'сотрудники', 'стоимость', '21', 'произошел', 'подчеркнул', 'пятницу', 'трех', 'агентства', 'затем', 'очередь', 'которое', '2013', 'нового', 'почти', '23', 'российский', 'информацию', 'другие', 'news', 'там', 'проект', '100', 'стала', 'очень', 'пост', 'вопрос', 'дел', 'проекта', 'две', 'обороны', '2006', 'совета', 'сотрудников', 'газа', 'версии', '2016', 'российские', '26', 'добавил', '27', 'тот', 'считает', 'своем', 'великобритании', 'источник', 'работу', '28', 'делу', 'оон', 'этих', 'граждан', 'службы', 'срок', 'поскольку', 'назвал', 'число', 'последние', 'действия', 'бывшего', 'данные', 'полиция', 'системы', 'идет', 'свой', 'группа', 'лидер', '40', 'назад', 'чего', 'даже', 'компаний', 'уголовное', 'дней', 'команды', 'одним', 'станет', 'впервые', 'итогам', 'новой', 'теперь', 'отмечается', 'дня', 'рынке', 'сети', 'слова', 'заявление', 'издания', 'администрации', 'интервью', 'примерно', 'заявила', 'должна', 'кто', 'дмитрий', 'комитета', 'помимо', 'деньги', 'средств', 'жителей', 'речь', 'новых', 'обвинения', 'программы', 'которую', 'этим', 'представителей', 'украине', 'мире', 'эта', 'помощи', 'эту', 'счет', 'новые', 'количество', 'детей', 'причиной', 'press', 'часов', 'сирии', 'вечером', 'ученые', 'банка', 'планируется', 'министра', 'операции', '29', 'нескольких', 'правоохранительных', 'воскресенье', 'жизни', 'сообщении', 'франции', 'грузии', 'тех', 'германии', 'выборах', 'ночь', 'произошло', 'пор', 'сайт', 'федерации', 'центре', 'игры', 'субботу', 'возможность', 'считают', 'ленты', 'полностью', 'органов', 'associated', 'самолет', 'оружия', 'свое', 'дом', 'шесть', 'чемпионата', 'газеты', 'месяцев', 'выборов', 'россию', 'военных', 'люди', 'состав', 'директор', 'национальной', 'некоторые', 'первого', 'квадратных', 'иностранных', '2005', 'получить', 'километров', 'руководство', 'деятельности', 'помощью', 'закон', 'доллара', 'являются', 'список']

In [66]:
probe_words = ["нефть", "российские", "рубля"]

for word in probe_words:
    if word in w2v_kv:
        print(f"\nmost_similar('{word}'):")
        print(w2v_kv.most_similar(word, topn=10))

most_similar('нефть'):
[('баррель', 0.7453940510749817), ('brent', 0.7320024967193604), ('барреля', 0.7158852815628052), ('нефти', 0.710671603679657), ('urals', 0.7054430246353149), ('североморскую', 0.6957404613494873), ('августовские', 0.6952854990959167), ('фьючерсов', 0.6924294233322144), ('фьючерсы', 0.6920465230941772), ('сырую', 0.6911002397537231)]

most_similar('российские'):
[('американские', 0.6857210993766785), ('отечественные', 0.6403515934944153), ('украинские', 0.6258518695831299), ('румынские', 0.6246842741966248), ('иностранные', 0.6242607235908508), ('казахстанские', 0.621875524520874), ('французские', 0.6100724339485168), ('норвежские', 0.6096036434173584), ('финские', 0.6043763160705566), ('европейские', 0.5916397571563721)]

most_similar('рубля'):
[('доллара', 0.8204084634780884), ('копеек', 0.8022236824035645), ('копейку', 0.778289794921875), ('копейки', 0.7685164213180542), ('доллар', 0.7628366947174072), ('бивалютная', 0.7212367653846741), ('рубль', 0.7168381214141846), ('иене', 0.6964298486709595), ('рублю', 0.6912440061569214), ('иены', 0.6813352704048157)]

In [67]:
triplets = [
    ["россия", "сша", "германии", "рубля"],
    ["банк", "нефть", "долларов", "самолет"],
    ["путин", "президент", "министр", "самолет"],
]

for words in triplets:
    existing = [w for w in words if w in w2v_kv]
    print(existing, "->", w2v_kv.doesnt_match(existing))

['россия', 'сша', 'германии', 'рубля'] -> рубля
['банк', 'нефть', 'долларов', 'самолет'] -> самолет
['путин', 'президент', 'министр', 'самолет'] -> самолет

intrinsic оценка эмбеддингов показала, что модель улавливает тематическую близость слов.
В целом качество обученных эмбеддингов можно считать приемлемым

## Navec

In [46]:
NAVEC_PATH = Path("navec_news_v1_1B_250K_300d_100q.tar")

if not NAVEC_PATH.exists():
    !wget -O {NAVEC_PATH} https://storage.yandexcloud.net/natasha-navec/packs/navec_news_v1_1B_250K_300d_100q.tar

assert NAVEC_PATH.exists(), "Не удалось скачать модель Navec"

--2026-03-14 16:45:43--  https://storage.yandexcloud.net/natasha-navec/packs/navec_news_v1_1B_250K_300d_100q.tar
Resolving mlcore-webproxy.mlcore-webproxy.svc.cluster.local (mlcore-webproxy.mlcore-webproxy.svc.cluster.local)... 10.32.0.166
Connecting to mlcore-webproxy.mlcore-webproxy.svc.cluster.local (mlcore-webproxy.mlcore-webproxy.svc.cluster.local)|10.32.0.166|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 26634240 (25M) [application/x-tar]
Saving to: ‘navec_news_v1_1B_250K_300d_100q.tar’

navec_news_v1_1B_25 100%[===================>]  25.40M  77.2MB/s    in 0.3s

2026-03-14 16:45:44 (77.2 MB/s) - ‘navec_news_v1_1B_250K_300d_100q.tar’ saved [26634240/26634240]

In [47]:
navec = Navec.load(str(NAVEC_PATH))
print("Navec loaded")
print("Размерность:", navec.pq.dim)

Navec loaded
Размерность: 300

## rus-vectores

In [53]:
import urllib.request
import gensim

urllib.request.urlretrieve(
    "https://rusvectores.org/static/models/rusvectores4/ruwikiruscorpora/ruwikiruscorpora_upos_skipgram_300_2_2018.vec.gz",
    "ruwikiruscorpora_upos_skipgram_300_2_2018.vec.gz"
)

model_ru = gensim.models.KeyedVectors.load_word2vec_format(
    "ruwikiruscorpora_upos_skipgram_300_2_2018.vec.gz",
    binary=False
)
model_ru.most_similar(positive=["ночь_NOUN"], topn=10)

[('ночь_PROPN', 0.7704508304595947),
 ('вечер_NOUN', 0.7683228254318237),
 ('утро_NOUN', 0.7520124316215515),
 ('полночь_NOUN', 0.7201331853866577),
 ('рассвет_NOUN', 0.6792924404144287),
 ('полдень_NOUN', 0.6637035012245178),
 ('утро_PROPN', 0.6531521677970886),
 ('ночь_ADV', 0.6248846650123596),
 ('сумерки_NOUN', 0.6227153539657593),
 ('ночью_NOUN', 0.6219336986541748)]

In [55]:
rusvectores_kv = model_ru

print("RusVectores loaded")
print("Размер словаря:", len(rusvectores_kv))
print("Размерность:", rusvectores_kv.vector_size)

RusVectores loaded
Размер словаря: 384764
Размерность: 300

In [68]:
def get_w2v_vector(token: str):
    if token in w2v_kv:
        return w2v_kv[token]
    return None

NAVEC_DIM = navec.pq.dim

def get_navec_vector(token: str):
    if token in navec:
        return navec[token]
    return None

RUSVEC_DIM = rusvectores_kv.vector_size

def get_rusvectores_vector(token: str):
    candidates = [
        token,
        f"{token}_NOUN",
        f"{token}_PROPN",
        f"{token}_ADJ",
        f"{token}_VERB",
        f"{token}_ADV",
    ]
    for cand in candidates:
        if cand in rusvectores_kv:
            return rusvectores_kv[cand]
    return None

In [70]:
# покрытие словаря

def embedding_coverage(tokens_list, get_vector_fn):
    total = 0
    found = 0
    for tokens in tokens_list:
        for token in tokens:
            total += 1
            if get_vector_fn(token) is not None:
                found += 1
    return found / total if total > 0 else 0.0


print(embedding_coverage(X_train_tokens, get_w2v_vector))
print(embedding_coverage(X_train_tokens, get_navec_vector))
print(embedding_coverage(X_train_tokens, get_rusvectores_vector))

0.9622206255164734
0.9406881557404163
0.5604244734433168

Покрытие словаря оказалось максимальным у собственного w2v и высоким у navec, тогда как у rus-vectores оно заметно ниже. Это ожидаемо, поскольку rus-vectores использует ключи формата lemma_POS, а в текущем пайплайне применялось лишь приближённое сопоставление токенов с несколькими возможными частями речи без полноценной лемматизации

In [71]:
def mean_pooling_vectors(tokens_list, get_vector_fn, dim):
    X = np.zeros((len(tokens_list), dim), dtype=np.float32)

    for i, tokens in enumerate(tqdm(tokens_list, desc="Vectorizing")):
        vectors = []
        for token in tokens:
            vec = get_vector_fn(token)
            if vec is not None:
                vectors.append(vec)

        if vectors:
            X[i] = np.mean(vectors, axis=0)

    return X

In [72]:
X_train_w2v = mean_pooling_vectors(X_train_tokens, get_w2v_vector, w2v_kv.vector_size)
X_valid_w2v = mean_pooling_vectors(X_valid_tokens, get_w2v_vector, w2v_kv.vector_size)
X_test_w2v  = mean_pooling_vectors(X_test_tokens,  get_w2v_vector, w2v_kv.vector_size)

Vectorizing:   0%|          | 0/60000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

In [73]:
X_train_navec = mean_pooling_vectors(X_train_tokens, get_navec_vector, NAVEC_DIM)
X_valid_navec = mean_pooling_vectors(X_valid_tokens, get_navec_vector, NAVEC_DIM)
X_test_navec  = mean_pooling_vectors(X_test_tokens,  get_navec_vector, NAVEC_DIM)

Vectorizing:   0%|          | 0/60000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

In [74]:
X_train_rusvec = mean_pooling_vectors(X_train_tokens, get_rusvectores_vector, RUSVEC_DIM)
X_valid_rusvec = mean_pooling_vectors(X_valid_tokens, get_rusvectores_vector, RUSVEC_DIM)
X_test_rusvec  = mean_pooling_vectors(X_test_tokens,  get_rusvectores_vector, RUSVEC_DIM)

Vectorizing:   0%|          | 0/60000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

Vectorizing:   0%|          | 0/20000 [00:00<?, ?it/s]

In [75]:
def fit_eval_logreg(X_train, y_train, X_valid, y_valid, name):
    clf = LogisticRegression(
        max_iter=500,
        solver="saga",
        verbose=1,
        multi_class="multinomial",
        n_jobs=-1,
        random_state=RANDOM_STATE
    )
    clf.fit(X_train, y_train)

    valid_pred = clf.predict(X_valid)

    return {
        "model": name,
        "valid_accuracy": accuracy_score(y_valid, valid_pred),
        "valid_macro_f1": f1_score(y_valid, valid_pred, average="macro"),
        "clf": clf}

results = []

results.append(fit_eval_logreg(X_train_w2v, y_train, X_valid_w2v, y_valid, "Word2Vec mean"))
results.append(fit_eval_logreg(X_train_navec, y_train, X_valid_navec, y_valid, "Navec mean"))
results.append(fit_eval_logreg(X_train_rusvec, y_train, X_valid_rusvec, y_valid, "RusVectores mean"))

results_df = pd.DataFrame([
    {k: v for k, v in row.items() if k != "clf"}
    for row in results
]).sort_values("valid_macro_f1", ascending=False)

results_df

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.

Epoch 1, change: 1
Epoch 2, change: 0.13289697
Epoch 3, change: 0.067943677
Epoch 4, change: 0.046195921
Epoch 5, change: 0.035057541
Epoch 6, change: 0.026700307
Epoch 7, change: 0.021355497
Epoch 8, change: 0.015639534
Epoch 9, change: 0.012343589
Epoch 10, change: 0.010679713
Epoch 11, change: 0.0086259888
Epoch 12, change: 0.0072071808
Epoch 13, change: 0.0055446355
Epoch 14, change: 0.0046034907
Epoch 15, change: 0.0039216792
Epoch 16, change: 0.0031741071
Epoch 17, change: 0.0027647919
Epoch 18, change: 0.0023275483
Epoch 19, change: 0.0021273778
Epoch 20, change: 0.0019924678
Epoch 21, change: 0.0018640643
Epoch 22, change: 0.0017640282
Epoch 23, change: 0.0016635741
Epoch 24, change: 0.0015796412
Epoch 25, change: 0.0015306076
Epoch 26, change: 0.0014594595
Epoch 27, change: 0.001330679
Epoch 28, change: 0.0012308072
Epoch 29, change: 0.0011760833
Epoch 30, change: 0.0011120215
Epoch 31, change: 0.0011028408
Epoch 32, change: 0.0010492377
Epoch 33, change: 0.001035742
Epoch 34, change: 0.0010002543
Epoch 35, change: 0.0009613111
Epoch 36, change: 0.00094822195
Epoch 37, change: 0.00089350238
Epoch 38, change: 0.00085288467
Epoch 39, change: 0.00074071123
Epoch 40, change: 0.0006950692
Epoch 41, change: 0.00065718603
Epoch 42, change: 0.00061694923
Epoch 43, change: 0.00060932233
Epoch 44, change: 0.00057810231
Epoch 45, change: 0.00056111807
Epoch 46, change: 0.00052932993
Epoch 47, change: 0.00052850426
Epoch 48, change: 0.00050908723
Epoch 49, change: 0.00051066937
Epoch 50, change: 0.00048663485
Epoch 51, change: 0.00049987459
Epoch 52, change: 0.00048461821
Epoch 53, change: 0.00044185185
Epoch 54, change: 0.00048166912
Epoch 55, change: 0.00043782868
Epoch 56, change: 0.00044252636
Epoch 57, change: 0.00041714273
Epoch 58, change: 0.00039923139
Epoch 59, change: 0.00038721328
Epoch 60, change: 0.00037341638
Epoch 61, change: 0.00034046729
Epoch 62, change: 0.00034393815
Epoch 63, change: 0.00030499871
Epoch 64, change: 0.00026119521
Epoch 65, change: 0.00022821961
Epoch 66, change: 0.00020350009
Epoch 67, change: 0.00018241341
Epoch 68, change: 0.00016569495
Epoch 69, change: 0.00015224797
Epoch 70, change: 0.00015274349
Epoch 71, change: 0.00016216218
Epoch 72, change: 0.00014825344
Epoch 73, change: 0.00013050834
Epoch 74, change: 0.00012266272
Epoch 75, change: 0.00012029876
Epoch 76, change: 0.00010952511
Epoch 77, change: 0.00013108675
Epoch 78, change: 0.00011128772
Epoch 79, change: 0.0001200898
Epoch 80, change: 0.00012985112
Epoch 81, change: 0.00010553121
Epoch 82, change: 0.00010645582
convergence after 83 epochs took 73 seconds

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.

Epoch 1, change: 1
Epoch 2, change: 0.1880431
Epoch 3, change: 0.10693125
Epoch 4, change: 0.069652401
Epoch 5, change: 0.051453803
Epoch 6, change: 0.036587723
Epoch 7, change: 0.028738484
Epoch 8, change: 0.028178325
Epoch 9, change: 0.018461769
Epoch 10, change: 0.016280364
Epoch 11, change: 0.013534416
Epoch 12, change: 0.0112827
Epoch 13, change: 0.0090978798
Epoch 14, change: 0.007966809
Epoch 15, change: 0.0068978518
Epoch 16, change: 0.005886869
Epoch 17, change: 0.0051383115
Epoch 18, change: 0.0046353019
Epoch 19, change: 0.004092813
Epoch 20, change: 0.0036071436
Epoch 21, change: 0.0031913924
Epoch 22, change: 0.0029221815
Epoch 23, change: 0.0027120861
Epoch 24, change: 0.0024989331
Epoch 25, change: 0.002283226
Epoch 26, change: 0.0021076133
Epoch 27, change: 0.0019638322
Epoch 28, change: 0.0017882579
Epoch 29, change: 0.0016494537
Epoch 30, change: 0.0015222876
Epoch 31, change: 0.001415165
Epoch 32, change: 0.0013111699
Epoch 33, change: 0.0012082049
Epoch 34, change: 0.001119973
Epoch 35, change: 0.0010224306
Epoch 36, change: 0.0010393277
Epoch 37, change: 0.00097192574
Epoch 38, change: 0.00105051
Epoch 39, change: 0.00099917571
Epoch 40, change: 0.0010241717
Epoch 41, change: 0.0010254838
Epoch 42, change: 0.00095447846
Epoch 43, change: 0.0010575043
Epoch 44, change: 0.00097923295
Epoch 45, change: 0.0010144586
Epoch 46, change: 0.0010015566
Epoch 47, change: 0.00091479765
Epoch 48, change: 0.0008149636
Epoch 49, change: 0.00073044735
Epoch 50, change: 0.00067662826
Epoch 51, change: 0.00064864563
Epoch 52, change: 0.00062304054
Epoch 53, change: 0.00060398004
Epoch 54, change: 0.00058706233
Epoch 55, change: 0.0005725965
Epoch 56, change: 0.00057205261
Epoch 57, change: 0.00056009268
Epoch 58, change: 0.00054817519
Epoch 59, change: 0.0005398154
Epoch 60, change: 0.000555281
Epoch 61, change: 0.0005245927
Epoch 62, change: 0.0005542094
Epoch 63, change: 0.0005260951
Epoch 64, change: 0.00055820157
Epoch 65, change: 0.00054069678
Epoch 66, change: 0.00055678753
Epoch 67, change: 0.00054956914
Epoch 68, change: 0.00052715949
Epoch 69, change: 0.00056129857
Epoch 70, change: 0.00052056141
Epoch 71, change: 0.00056805147
Epoch 72, change: 0.00052818324
Epoch 73, change: 0.00057973288
Epoch 74, change: 0.00053853344
Epoch 75, change: 0.00055472576
Epoch 76, change: 0.00054619554
Epoch 77, change: 0.00055469899
Epoch 78, change: 0.00054712594
Epoch 79, change: 0.00052513916
Epoch 80, change: 0.00052345672
Epoch 81, change: 0.0005328671
Epoch 82, change: 0.00053719961
Epoch 83, change: 0.00054227188
Epoch 84, change: 0.00054187002
Epoch 85, change: 0.00052750902
Epoch 86, change: 0.00052359799
Epoch 87, change: 0.00051866652
Epoch 88, change: 0.00052583311
Epoch 89, change: 0.00051072979
Epoch 90, change: 0.00050735218
Epoch 91, change: 0.00051324489
Epoch 92, change: 0.00050014013
Epoch 93, change: 0.0005044195
Epoch 94, change: 0.00048427758
Epoch 95, change: 0.00047319118
Epoch 96, change: 0.00045303578
Epoch 97, change: 0.00042295441
Epoch 98, change: 0.00038196717
Epoch 99, change: 0.00033953146
Epoch 100, change: 0.0003131493
Epoch 101, change: 0.00028143844
Epoch 102, change: 0.00025521652
Epoch 103, change: 0.00023087849
Epoch 104, change: 0.00021189111
Epoch 105, change: 0.00019239595
Epoch 106, change: 0.00017849074
Epoch 107, change: 0.00016401857
Epoch 108, change: 0.00015128465
Epoch 109, change: 0.00014944733
Epoch 110, change: 0.00017626176
Epoch 111, change: 0.00014923712
Epoch 112, change: 0.00017571374
Epoch 113, change: 0.00015262698
Epoch 114, change: 0.00011962975
Epoch 115, change: 0.00014443602
Epoch 116, change: 0.00018110654
Epoch 117, change: 0.00018002409
Epoch 118, change: 0.00014222282
Epoch 119, change: 0.00012149506
Epoch 120, change: 0.00017847573
Epoch 121, change: 0.00018160071
Epoch 122, change: 0.0001454735
Epoch 123, change: 0.00015960154
Epoch 124, change: 0.00013953353
Epoch 125, change: 0.00016779255
Epoch 126, change: 0.0001785387
Epoch 127, change: 0.00018659598
Epoch 128, change: 0.00014681328
Epoch 129, change: 0.00010885119
Epoch 130, change: 0.0001469269
Epoch 131, change: 0.00016245697
Epoch 132, change: 0.00014811089
Epoch 133, change: 0.00018129162
Epoch 134, change: 0.00012737479
Epoch 135, change: 0.00015177712
Epoch 136, change: 0.00017420905
Epoch 137, change: 0.00014083441
Epoch 138, change: 0.00014940544
Epoch 139, change: 0.00014466913
Epoch 140, change: 0.00016014444
Epoch 141, change: 0.00014546908
Epoch 142, change: 0.00018724697
Epoch 143, change: 0.00016992807
Epoch 144, change: 0.00014137705
Epoch 145, change: 0.00012810327
Epoch 146, change: 0.00017164293
Epoch 147, change: 0.00014035104
Epoch 148, change: 0.00018328185
Epoch 149, change: 0.0001640369
Epoch 150, change: 0.00012740721
Epoch 151, change: 0.00014063122
Epoch 152, change: 0.00014386114
Epoch 153, change: 0.00018091309
Epoch 154, change: 0.00017421883
Epoch 155, change: 0.0001741241
Epoch 156, change: 0.00018881586
Epoch 157, change: 0.00014122389
Epoch 158, change: 0.0001268169
Epoch 159, change: 0.00017132843
Epoch 160, change: 0.0001346412
Epoch 161, change: 0.00017541545
Epoch 162, change: 0.00017872745
Epoch 163, change: 0.00017283483
Epoch 164, change: 0.00016637243
Epoch 165, change: 0.0001693322
Epoch 166, change: 0.00015006821
Epoch 167, change: 0.00016906582
Epoch 168, change: 0.00014564843
Epoch 169, change: 0.00017358438
Epoch 170, change: 0.00014237489
Epoch 171, change: 0.00017715173
Epoch 172, change: 0.000172307
Epoch 173, change: 0.00013475429
Epoch 174, change: 0.00017736772
Epoch 175, change: 0.00017451939
Epoch 176, change: 0.00016113253
Epoch 177, change: 0.00016733482
Epoch 178, change: 0.00015368726
Epoch 179, change: 0.00012575148
Epoch 180, change: 0.00012094511
Epoch 181, change: 0.00012737093
Epoch 182, change: 0.00016561104
Epoch 183, change: 0.00014195172
Epoch 184, change: 0.00013868722
Epoch 185, change: 0.00017813029
Epoch 186, change: 0.00017742183
Epoch 187, change: 0.00016787273
Epoch 188, change: 0.0001039562
Epoch 189, change: 0.00015029094
Epoch 190, change: 0.00014139868
Epoch 191, change: 0.00014176928
Epoch 192, change: 0.00019565254
Epoch 193, change: 0.00017052643
Epoch 194, change: 0.00013518591
Epoch 195, change: 0.00014253161
Epoch 196, change: 0.0001150134
Epoch 197, change: 0.00015763899
convergence after 198 epochs took 256 seconds

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.

Epoch 1, change: 1
Epoch 2, change: 0.17750409
Epoch 3, change: 0.056719121
Epoch 4, change: 0.042610433
Epoch 5, change: 0.018368538
Epoch 6, change: 0.010843163
Epoch 7, change: 0.007619123
Epoch 8, change: 0.0053913351
Epoch 9, change: 0.00303673
Epoch 10, change: 0.002093629
Epoch 11, change: 0.001949748
Epoch 12, change: 0.0010909371
Epoch 13, change: 0.00052337721
Epoch 14, change: 0.00035195972
Epoch 15, change: 0.00019934599
Epoch 16, change: 0.00014286446
convergence after 17 epochs took 22 seconds

              model  valid_accuracy  valid_macro_f1
1        Navec mean         0.78940        0.557469
0     Word2Vec mean         0.77995        0.541244
2  RusVectores mean         0.71015        0.412856

In [76]:
best_row = max(results, key=lambda x: x["valid_macro_f1"])
best_name = best_row["model"]
print("Лучший набор эмбеддингов на val:", best_name)

Лучший набор эмбеддингов на val: Navec mean

In [77]:
# автовыбор для воспроизводимости пайплайна

if best_name == "Word2Vec mean":
    best_get_vector = get_w2v_vector
    BEST_DIM = w2v_kv.vector_size
elif best_name == "Navec mean":
    best_get_vector = get_navec_vector
    BEST_DIM = navec.pq.dim
else:
    best_get_vector = get_rusvectores_vector
    BEST_DIM = rusvectores_kv.vector_size

print(BEST_DIM)

300

## tfidf weighted avg

In [78]:
tfidf = TfidfVectorizer(
    tokenizer=lambda x: x,
    preprocessor=lambda x: x,
    token_pattern=None,
    min_df=5,
    max_df=0.95
)

tfidf.fit(X_train_tokens)
print(len(tfidf.vocabulary_))

96763

In [80]:
def tfidf_weighted_embeddings(tokens_list, tfidf_vectorizer, get_vector_fn, dim):
    X_tfidf = tfidf_vectorizer.transform(tokens_list)
    feature_names = tfidf_vectorizer.get_feature_names_out()

    X = np.zeros((len(tokens_list), dim), dtype=np.float32)

    for i in tqdm(range(X_tfidf.shape[0]), desc="TF-IDF weighted embeddings"):
        row = X_tfidf[i]
        if row.nnz == 0:
            continue

        weighted_sum = np.zeros(dim, dtype=np.float32)
        weight_total = 0.0

        for idx, weight in zip(row.indices, row.data):
            token = feature_names[idx]
            vec = get_vector_fn(token)
            if vec is not None:
                weighted_sum += weight * vec
                weight_total += weight

        if weight_total > 0:
            X[i] = weighted_sum / weight_total

    return X


X_train_best_tfidf = tfidf_weighted_embeddings(X_train_tokens, tfidf, best_get_vector, BEST_DIM)
X_valid_best_tfidf = tfidf_weighted_embeddings(X_valid_tokens, tfidf, best_get_vector, BEST_DIM)
X_test_best_tfidf  = tfidf_weighted_embeddings(X_test_tokens,  tfidf, best_get_vector, BEST_DIM)

TF-IDF weighted embeddings:   0%|          | 0/60000 [00:00<?, ?it/s]

TF-IDF weighted embeddings:   0%|          | 0/20000 [00:00<?, ?it/s]

TF-IDF weighted embeddings:   0%|          | 0/20000 [00:00<?, ?it/s]

In [81]:
tfidf_emb_result = fit_eval_logreg(
    X_train_best_tfidf, y_train,
    X_valid_best_tfidf, y_valid,
    f"{best_name} + TF-IDF weighted"
)

pd.DataFrame([{
    k: v for k, v in tfidf_emb_result.items() if k != "clf"
}])

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 12 concurrent workers.

Epoch 1, change: 1
Epoch 2, change: 0.21552482
Epoch 3, change: 0.10587612
Epoch 4, change: 0.089359298
Epoch 5, change: 0.060005438
Epoch 6, change: 0.039998822
Epoch 7, change: 0.031096507
Epoch 8, change: 0.029871687
Epoch 9, change: 0.020063164
Epoch 10, change: 0.016720925
Epoch 11, change: 0.014630031
Epoch 12, change: 0.012971854
Epoch 13, change: 0.010958908
Epoch 14, change: 0.010155462
Epoch 15, change: 0.0086390469
Epoch 16, change: 0.0078104963
Epoch 17, change: 0.0068702735
Epoch 18, change: 0.0058081071
Epoch 19, change: 0.0054308721
Epoch 20, change: 0.0048467722
Epoch 21, change: 0.0043664421
Epoch 22, change: 0.0039866325
Epoch 23, change: 0.0035812533
Epoch 24, change: 0.0032464075
Epoch 25, change: 0.0030978401
Epoch 26, change: 0.0027105135
Epoch 27, change: 0.0025139095
Epoch 28, change: 0.0023397342
Epoch 29, change: 0.0022356326
Epoch 30, change: 0.0021473672
Epoch 31, change: 0.0021228374
Epoch 32, change: 0.0020398186
Epoch 33, change: 0.0019099284
Epoch 34, change: 0.0016829442
Epoch 35, change: 0.0015987676
Epoch 36, change: 0.0013050888
Epoch 37, change: 0.0012427476
Epoch 38, change: 0.0011369836
Epoch 39, change: 0.0010844038
Epoch 40, change: 0.0010440317
Epoch 41, change: 0.00099228951
Epoch 42, change: 0.00098501053
Epoch 43, change: 0.00096317189
Epoch 44, change: 0.00094784942
Epoch 45, change: 0.00096085662
Epoch 46, change: 0.00094777963
Epoch 47, change: 0.00094102853
Epoch 48, change: 0.00093058083
Epoch 49, change: 0.00091603777
Epoch 50, change: 0.00091518561
Epoch 51, change: 0.00092196197
Epoch 52, change: 0.00090294599
Epoch 53, change: 0.00087610522
Epoch 54, change: 0.00088948634
Epoch 55, change: 0.00090061384
Epoch 56, change: 0.00087555608
Epoch 57, change: 0.00085198373
Epoch 58, change: 0.0008722737
Epoch 59, change: 0.00085874018
Epoch 60, change: 0.00084988837
Epoch 61, change: 0.00076673506
Epoch 62, change: 0.00071167329
Epoch 63, change: 0.00063754112
Epoch 64, change: 0.00057927909
Epoch 65, change: 0.00051961542
Epoch 66, change: 0.0004694708
Epoch 67, change: 0.00043299157
Epoch 68, change: 0.00039359732
Epoch 69, change: 0.00036084853
Epoch 70, change: 0.0003307554
Epoch 71, change: 0.00030806006
Epoch 72, change: 0.00027911874
Epoch 73, change: 0.00026189964
Epoch 74, change: 0.0002400935
Epoch 75, change: 0.00021468877
Epoch 76, change: 0.00020052625
Epoch 77, change: 0.00023715342
Epoch 78, change: 0.00018245194
Epoch 79, change: 0.00016323524
Epoch 80, change: 0.00017843281
Epoch 81, change: 0.0002002586
Epoch 82, change: 0.00020809175
Epoch 83, change: 0.00013554534
Epoch 84, change: 0.00021960484
Epoch 85, change: 0.00017165631
Epoch 86, change: 0.00020533134
Epoch 87, change: 0.00016918078
Epoch 88, change: 0.0002023242
Epoch 89, change: 0.00022896944
Epoch 90, change: 0.00024989175
Epoch 91, change: 0.00023564458
Epoch 92, change: 0.00021201539
Epoch 93, change: 0.00020264513
Epoch 94, change: 0.00015016025
Epoch 95, change: 0.00016944084
Epoch 96, change: 0.00022942793
Epoch 97, change: 0.00017500234
Epoch 98, change: 0.00018122766
Epoch 99, change: 0.00020717183
Epoch 100, change: 0.00015016596
Epoch 101, change: 0.00020145005
Epoch 102, change: 0.00020091562
Epoch 103, change: 0.00019488999
Epoch 104, change: 0.0001371127
Epoch 105, change: 0.0002027094
Epoch 106, change: 0.00019032728
Epoch 107, change: 0.00016562553
Epoch 108, change: 0.00018852061
Epoch 109, change: 0.00026604917
Epoch 110, change: 0.00016529312
Epoch 111, change: 0.00016867083
Epoch 112, change: 0.00022313498
Epoch 113, change: 0.00016944337
Epoch 114, change: 0.00017941876
Epoch 115, change: 0.00018048384
Epoch 116, change: 0.00015183038
Epoch 117, change: 0.00022660937
Epoch 118, change: 0.00018202519
Epoch 119, change: 0.00020632763
Epoch 120, change: 0.00016214493
Epoch 121, change: 0.00024499043
Epoch 122, change: 0.0001751933
Epoch 123, change: 0.00025479469
Epoch 124, change: 0.00016502256
Epoch 125, change: 0.0002428148
Epoch 126, change: 0.00017760159
Epoch 127, change: 0.00017626614
Epoch 128, change: 0.00019072837
Epoch 129, change: 0.0002474678
Epoch 130, change: 0.00020351881
Epoch 131, change: 0.00018129246
Epoch 132, change: 0.00019013113
Epoch 133, change: 0.00017566461
Epoch 134, change: 0.00019347233
Epoch 135, change: 0.00023411309
Epoch 136, change: 0.00024435855
Epoch 137, change: 0.00016736901
Epoch 138, change: 0.00018330321
Epoch 139, change: 0.00022166623
Epoch 140, change: 0.00018665167
Epoch 141, change: 0.00021436989
Epoch 142, change: 0.00014681816
Epoch 143, change: 0.00023491135
Epoch 144, change: 0.00020786776
Epoch 145, change: 0.00021302442
Epoch 146, change: 0.00016957651
Epoch 147, change: 0.00017453122
Epoch 148, change: 0.00014989657
Epoch 149, change: 0.00014400619
Epoch 150, change: 0.00017887373
Epoch 151, change: 0.00023993102
Epoch 152, change: 0.00023163074
Epoch 153, change: 0.00017787596
Epoch 154, change: 0.00018289679
Epoch 155, change: 0.00018296587
Epoch 156, change: 0.00018919491
Epoch 157, change: 0.00019388016
Epoch 158, change: 0.00016837429
Epoch 159, change: 0.00021035112
Epoch 160, change: 0.00020948242
Epoch 161, change: 0.00022334303
Epoch 162, change: 0.00019696238
Epoch 163, change: 0.00020363447
Epoch 164, change: 0.00017619022
Epoch 165, change: 0.00024842136
Epoch 166, change: 0.0002262005
Epoch 167, change: 0.00016896654
Epoch 168, change: 0.00019109141
Epoch 169, change: 0.0002312938
Epoch 170, change: 0.00017546394
Epoch 171, change: 0.00021730716
Epoch 172, change: 0.00022380055
Epoch 173, change: 0.00016087263
Epoch 174, change: 0.00024325027
Epoch 175, change: 0.00017841293
Epoch 176, change: 0.0002392507
Epoch 177, change: 0.00015296463
Epoch 178, change: 0.00016113379
Epoch 179, change: 0.00019892343
Epoch 180, change: 0.00015658326
Epoch 181, change: 0.00017332034
Epoch 182, change: 0.0002379264
Epoch 183, change: 0.00019588359
Epoch 184, change: 0.0001636854
Epoch 185, change: 0.00021148744
Epoch 186, change: 0.00016964538
Epoch 187, change: 0.00017613938
Epoch 188, change: 0.00016924512
Epoch 189, change: 0.00013853316
Epoch 190, change: 0.0002371333
Epoch 191, change: 0.00023117354
Epoch 192, change: 0.00022722683
Epoch 193, change: 0.00019870694
Epoch 194, change: 0.00022769634
Epoch 195, change: 0.00016971886
Epoch 196, change: 0.00017949294
Epoch 197, change: 0.00015612868
Epoch 198, change: 0.00021273625
Epoch 199, change: 0.00019917804
Epoch 200, change: 0.00019214219
Epoch 201, change: 0.00015666048
Epoch 202, change: 0.00023184541
Epoch 203, change: 0.00014668702
Epoch 204, change: 0.00016422886
Epoch 205, change: 0.00020687473
Epoch 206, change: 0.00019106842
Epoch 207, change: 0.00019117167
Epoch 208, change: 0.00016717125
Epoch 209, change: 0.00017406774
Epoch 210, change: 0.00014969926
Epoch 211, change: 0.0002316445
Epoch 212, change: 0.0002240152
Epoch 213, change: 0.00020326165
Epoch 214, change: 0.00022194051
Epoch 215, change: 0.00016168597
Epoch 216, change: 0.00023426126
Epoch 217, change: 0.00017119356
Epoch 218, change: 0.00017849106
Epoch 219, change: 0.00015044003
Epoch 220, change: 0.0002027958
Epoch 221, change: 0.00019442874
Epoch 222, change: 0.00016838343
Epoch 223, change: 0.00013363616
Epoch 224, change: 0.00022937819
Epoch 225, change: 0.00022368823
Epoch 226, change: 0.00015044129
Epoch 227, change: 0.00017180121
Epoch 228, change: 0.00021592346
Epoch 229, change: 0.0002293109
Epoch 230, change: 0.00021699145
Epoch 231, change: 0.00021216775
Epoch 232, change: 0.00021990224
Epoch 233, change: 0.0001559935
Epoch 234, change: 0.00017909265
Epoch 235, change: 0.00022575777
Epoch 236, change: 0.0002011867
Epoch 237, change: 0.00021014558
Epoch 238, change: 0.00015284162
Epoch 239, change: 0.00014266575
Epoch 240, change: 0.00023599211
Epoch 241, change: 0.00022648754
Epoch 242, change: 0.00016844354
Epoch 243, change: 0.00016563172
Epoch 244, change: 0.00014467916
Epoch 245, change: 0.00022394715
Epoch 246, change: 0.00022314556
Epoch 247, change: 0.00015431987
Epoch 248, change: 0.00017514292
Epoch 249, change: 0.00023486263
Epoch 250, change: 0.00022113914
Epoch 251, change: 0.00017179623
Epoch 252, change: 0.00014822902
Epoch 253, change: 0.00022930918
Epoch 254, change: 0.00023827901
Epoch 255, change: 0.00020159014
Epoch 256, change: 0.00016577067
Epoch 257, change: 0.00014796306
Epoch 258, change: 0.00021940193
Epoch 259, change: 0.00021551909
Epoch 260, change: 0.00015519488
Epoch 261, change: 0.00015566425
Epoch 262, change: 0.00016778204
Epoch 263, change: 0.00016008338
Epoch 264, change: 0.00015512866
Epoch 265, change: 0.00015660317
Epoch 266, change: 0.00022589481
Epoch 267, change: 0.00015780625
Epoch 268, change: 0.00022268298
Epoch 269, change: 0.0001667769
Epoch 270, change: 0.00021411288
Epoch 271, change: 0.0002194683
Epoch 272, change: 0.00015673395
Epoch 273, change: 0.00017146382
Epoch 274, change: 0.00016289398
Epoch 275, change: 0.0001455554
Epoch 276, change: 0.00022509407
Epoch 277, change: 0.00017575055
Epoch 278, change: 0.00019242261
Epoch 279, change: 0.00023647503
Epoch 280, change: 0.00016918374
Epoch 281, change: 0.00022582611
Epoch 282, change: 0.00015987748
Epoch 283, change: 0.00020398811
Epoch 284, change: 0.0001457466
Epoch 285, change: 0.00018377298
Epoch 286, change: 0.0001527104
Epoch 287, change: 0.00022742443
Epoch 288, change: 0.00024818038
Epoch 289, change: 0.00025668286
Epoch 290, change: 0.00020828187
Epoch 291, change: 0.00020982281
Epoch 292, change: 0.00020121958
Epoch 293, change: 0.00020620842
Epoch 294, change: 0.00019054132
Epoch 295, change: 0.00022529114
Epoch 296, change: 0.00019295329
Epoch 297, change: 0.00020667761
Epoch 298, change: 0.0002372404
Epoch 299, change: 0.0001779579
Epoch 300, change: 0.00023406337
Epoch 301, change: 0.00020072061
Epoch 302, change: 0.00016389716
Epoch 303, change: 0.00015131068
Epoch 304, change: 0.00023419778
Epoch 305, change: 0.00014448199
Epoch 306, change: 0.00020105566
Epoch 307, change: 0.00017581535
Epoch 308, change: 0.00014736287
Epoch 309, change: 0.00016771421
Epoch 310, change: 0.00019801705
Epoch 311, change: 0.00020210347
Epoch 312, change: 0.00022637582
Epoch 313, change: 0.00020498713
Epoch 314, change: 0.00015310588
Epoch 315, change: 0.00013991875
Epoch 316, change: 0.00015665665
Epoch 317, change: 0.00014808709
Epoch 318, change: 0.00013623918
Epoch 319, change: 0.00019622606
Epoch 320, change: 0.00016255144
Epoch 321, change: 0.0001463504
Epoch 322, change: 0.00021999539
Epoch 323, change: 0.00019716521
Epoch 324, change: 0.00014273678
Epoch 325, change: 0.00018759457
Epoch 326, change: 0.00014528127
Epoch 327, change: 0.00024215929
Epoch 328, change: 0.00016744385
Epoch 329, change: 0.00015043851
Epoch 330, change: 0.00015284958
Epoch 331, change: 0.00017936196
Epoch 332, change: 0.0001951637
Epoch 333, change: 0.0002346644
Epoch 334, change: 0.0002421285
Epoch 335, change: 0.00019121375
Epoch 336, change: 0.00015044
Epoch 337, change: 0.00017655338
Epoch 338, change: 0.00020868814
Epoch 339, change: 0.00019636985
Epoch 340, change: 0.00024049047
Epoch 341, change: 0.00016082042
Epoch 342, change: 0.00014408139
Epoch 343, change: 0.00019971855
Epoch 344, change: 0.00019409547
Epoch 345, change: 0.00021029718
Epoch 346, change: 0.00014662542
Epoch 347, change: 0.0001876006
Epoch 348, change: 0.00018960869
Epoch 349, change: 0.00020453861
Epoch 350, change: 0.00018833946
Epoch 351, change: 0.00019992286
Epoch 352, change: 0.00015258494
Epoch 353, change: 0.00017602069
Epoch 354, change: 0.0002127114
Epoch 355, change: 0.00013983104
Epoch 356, change: 0.00015914709
Epoch 357, change: 0.00013832537
Epoch 358, change: 0.00017956737
Epoch 359, change: 0.00020828001
Epoch 360, change: 0.0002242819
Epoch 361, change: 0.00014032813
Epoch 362, change: 0.00018317602
Epoch 363, change: 0.00016490028
Epoch 364, change: 0.00019897912
Epoch 365, change: 0.00018505409
Epoch 366, change: 0.0001588741
Epoch 367, change: 0.00014655637
Epoch 368, change: 0.00017286936
Epoch 369, change: 0.00021645353
Epoch 370, change: 0.00018646092
Epoch 371, change: 0.00013892607
Epoch 372, change: 0.00018277857
Epoch 373, change: 0.00017648572
Epoch 374, change: 0.00017521177
Epoch 375, change: 0.00023486675
Epoch 376, change: 0.00017795835
Epoch 377, change: 0.00016048385
Epoch 378, change: 0.00019831269
Epoch 379, change: 0.00016081885
Epoch 380, change: 0.00018860491
Epoch 381, change: 0.00014826552
Epoch 382, change: 0.00022362138
Epoch 383, change: 0.00018043566
Epoch 384, change: 0.00013624936
Epoch 385, change: 0.00020132806
Epoch 386, change: 0.00018003528
Epoch 387, change: 0.00014381394
Epoch 388, change: 0.00020393904
Epoch 389, change: 0.00014856772
Epoch 390, change: 0.00016236069
Epoch 391, change: 0.00021699289
Epoch 392, change: 0.00021565474
Epoch 393, change: 0.00015974932
Epoch 394, change: 0.00018137536
Epoch 395, change: 0.0001795679
Epoch 396, change: 0.00021980597
Epoch 397, change: 0.00014408234
Epoch 398, change: 0.00018170952
Epoch 399, change: 0.00013792326
Epoch 400, change: 0.00016524059
Epoch 401, change: 0.00025358624
Epoch 402, change: 0.0002249644
Epoch 403, change: 0.00017682454
Epoch 404, change: 0.00023005226
Epoch 405, change: 0.00019108527
Epoch 406, change: 0.00015901419
Epoch 407, change: 0.00020943128
Epoch 408, change: 0.00017648998
Epoch 409, change: 0.00022382526
Epoch 410, change: 0.00020568023
Epoch 411, change: 0.00016410238
Epoch 412, change: 0.00022509626
Epoch 413, change: 0.00015693906
Epoch 414, change: 0.000181108
Epoch 415, change: 0.00015131611
Epoch 416, change: 0.00016229485
Epoch 417, change: 0.0002574703
Epoch 418, change: 0.00022730826
Epoch 419, change: 0.00018218155
Epoch 420, change: 0.00019958912
Epoch 421, change: 0.0001521184
Epoch 422, change: 0.00016704966
Epoch 423, change: 0.0001699289
Epoch 424, change: 0.00017126843
Epoch 425, change: 0.00024632266
Epoch 426, change: 0.00020561444
Epoch 427, change: 0.00015011073
Epoch 428, change: 0.00017066509
Epoch 429, change: 0.00016015294
Epoch 430, change: 0.00016771787
Epoch 431, change: 0.0002323963
Epoch 432, change: 0.00022255462
Epoch 433, change: 0.00018425639
Epoch 434, change: 0.00014823595
Epoch 435, change: 0.00015807796
Epoch 436, change: 0.00020769038
Epoch 437, change: 0.00015633662
Epoch 438, change: 0.0002021314
Epoch 439, change: 0.00019744593
Epoch 440, change: 0.00019925441
Epoch 441, change: 0.0001574748
Epoch 442, change: 0.0001779633
Epoch 443, change: 0.00015459719
Epoch 444, change: 0.00018927705
Epoch 445, change: 0.00015887979
Epoch 446, change: 0.00020340529
Epoch 447, change: 0.00017943686
Epoch 448, change: 0.00024049832
Epoch 449, change: 0.00015118014
Epoch 450, change: 0.00015612433
Epoch 451, change: 0.00025092493
Epoch 452, change: 0.00022896726
Epoch 453, change: 0.00015692966
Epoch 454, change: 0.00026803353
Epoch 455, change: 0.0001464174
Epoch 456, change: 0.00019047353
Epoch 457, change: 0.00023847632
Epoch 458, change: 0.0001967679
Epoch 459, change: 0.00016396225
Epoch 460, change: 0.0001420028
Epoch 461, change: 0.00024350034
Epoch 462, change: 0.00017045673
Epoch 463, change: 0.00016563639
Epoch 464, change: 0.00017119429
Epoch 465, change: 0.00018978379
Epoch 466, change: 0.00016428161
Epoch 467, change: 0.00018644238
Epoch 468, change: 0.00016408268
Epoch 469, change: 0.00016662925
Epoch 470, change: 0.00017881431
Epoch 471, change: 0.00015290707
Epoch 472, change: 0.00019260764
Epoch 473, change: 0.00020740433
Epoch 474, change: 0.00016087676
Epoch 475, change: 0.00018156398
Epoch 476, change: 0.00015317774
Epoch 477, change: 0.00019361508
Epoch 478, change: 0.0001675737
Epoch 479, change: 0.00023914292
Epoch 480, change: 0.0001667727
Epoch 481, change: 0.00022361348
Epoch 482, change: 0.00016991989
Epoch 483, change: 0.00018799698
Epoch 484, change: 0.00017293422
Epoch 485, change: 0.00022897165
Epoch 486, change: 0.00019188023
Epoch 487, change: 0.00018096727
Epoch 488, change: 0.00023740738
Epoch 489, change: 0.00019194894
Epoch 490, change: 0.00015177729
Epoch 491, change: 0.00023278923
Epoch 492, change: 0.00019295279
Epoch 493, change: 0.00015451889
Epoch 494, change: 0.00018846369
Epoch 495, change: 0.00017467294
Epoch 496, change: 0.00017012059
Epoch 497, change: 0.00023097867
Epoch 498, change: 0.00016617069
Epoch 499, change: 0.00014508204
max_iter reached after 653 secondsEpoch 500, change: 0.00022810213

                          model  valid_accuracy  valid_macro_f1
0  Navec mean + TF-IDF weighted         0.78865        0.562871

In [82]:
trained_models = {row["model"]: row["clf"] for row in results}
trained_models[tfidf_emb_result["model"]] = tfidf_emb_result["clf"]

In [83]:
test_results = []

pred = trained_models["Word2Vec mean"].predict(X_test_w2v)
test_results.append({
    "model": "Word2Vec mean",
    "test_accuracy": accuracy_score(y_test, pred),
    "test_macro_f1": f1_score(y_test, pred, average="macro")
})

pred = trained_models["Navec mean"].predict(X_test_navec)
test_results.append({
    "model": "Navec mean",
    "test_accuracy": accuracy_score(y_test, pred),
    "test_macro_f1": f1_score(y_test, pred, average="macro")
})

pred = trained_models["RusVectores mean"].predict(X_test_rusvec)
test_results.append({
    "model": "RusVectores mean",
    "test_accuracy": accuracy_score(y_test, pred),
    "test_macro_f1": f1_score(y_test, pred, average="macro")
})

pred = trained_models[f"{best_name} + TF-IDF weighted"].predict(X_test_best_tfidf)
test_results.append({
    "model": f"{best_name} + TF-IDF weighted",
    "test_accuracy": accuracy_score(y_test, pred),
    "test_macro_f1": f1_score(y_test, pred, average="macro")
})

test_results_df = pd.DataFrame(test_results).sort_values("test_macro_f1", ascending=False)
test_results_df

                          model  test_accuracy  test_macro_f1
3  Navec mean + TF-IDF weighted        0.78780       0.570545
1                    Navec mean        0.78825       0.561815
0                 Word2Vec mean        0.77745       0.536563
2              RusVectores mean        0.71320       0.416954

In [85]:
best_test_model_name = test_results_df.iloc[0]["model"]
print("Лучшая модель на test:", best_test_model_name)

Лучшая модель на test: Navec mean + TF-IDF weighted

In [86]:
if best_test_model_name == "Word2Vec mean":
    best_test_pred = trained_models[best_test_model_name].predict(X_test_w2v)
elif best_test_model_name == "Navec mean":
    best_test_pred = trained_models[best_test_model_name].predict(X_test_navec)
elif best_test_model_name == "RusVectores mean":
    best_test_pred = trained_models[best_test_model_name].predict(X_test_rusvec)
else:
    best_test_pred = trained_models[best_test_model_name].predict(X_test_best_tfidf)

print(classification_report(y_test, best_test_pred))

                   precision    recall  f1-score   support

   69-я параллель       0.82      0.26      0.40        34
           Бизнес       0.54      0.21      0.31       200
      Бывший СССР       0.81      0.77      0.79      1445
              Дом       0.82      0.76      0.79       588
         Из жизни       0.63      0.54      0.58       747
   Интернет и СМИ       0.74      0.67      0.70      1209
             Крым       0.00      0.00      0.00        18
     Культпросвет       0.00      0.00      0.00         9
         Культура       0.84      0.86      0.85      1456
          Легпром       0.00      0.00      0.00         3
              Мир       0.78      0.84      0.81      3699
  Наука и техника       0.79      0.83      0.81      1438
      Путешествия       0.64      0.47      0.54       174
           Россия       0.75      0.81      0.78      4344
Силовые структуры       0.45      0.24      0.31       531
            Спорт       0.96      0.96      0.96      1743
         Ценности       0.88      0.76      0.82       210
        Экономика       0.81      0.85      0.83      2152

         accuracy                           0.79     20000
        macro avg       0.63      0.55      0.57     20000
     weighted avg       0.78      0.79      0.78     20000

## Вывод

Лучший результат на тестовой выборке показала модель **Navec mean + TF-IDF weighted**: `accuracy = 0.7878`, `macro_f1 = 0.5705`. Обычное усреднение эмбеддингов `Navec` также показало сильный результат (`accuracy = 0.7883`, `macro_f1 = 0.5618`), однако tf-idf-взвешивание позволило немного улучшить `macro_f1`, что особенно важно при несбалансированных классах.

Собственный `Word2Vec` показал результат ниже (`accuracy = 0.7775`, `macro_f1 = 0.5366`), но всё равно остался конкурентоспособным. `RusVectores` сработал заметно хуже (`accuracy = 0.7132`, `macro_f1 = 0.4170`), что согласуется с более низким покрытием словаря. Вероятная причина заключается в том, что `RusVectores` использует представление слов в формате `lemma_POS`, а у нас не применялась полноценная лемматизация и морфологическая разметка.

По `classification_report` видно, что модель хорошо распознаёт крупные и тематически устойчивые классы, такие как **«Спорт»**, **«Культура»**, **«Наука и техника»**, **«Экономика»**, **«Россия»** и **«Мир»**. Наиболее слабые результаты наблюдаются на редких классах, например **«Крым»**, **«Культпросвет»**, **«Легпром»** и **«69-я параллель»**, что ожидаемо из-за малого числа примеров и дисбаланса классов.